//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LuotXemTai
    {
        public int Id { get; set; }
        public Nullable<int> MaLuotXemTai { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> Xem { get; set; }
        public Nullable<int> Tai { get; set; }
    
        public virtual LuotXemTai LuotXemTai { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
