//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAQ()
        {
            this.FAQ_NoiDung = new HashSet<FAQ_NoiDung>();
        }
    
        public int Id { get; set; }
        public string CauHoi { get; set; }
        public string TraLoi { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public Nullable<int> STT { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAQ_NoiDung> FAQ_NoiDung { get; set; }
    }
}
