//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ_NoiDung
    {
        public int Id { get; set; }
        public string CauHoi { get; set; }
        public string TraLoi { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual FAQ FAQ { get; set; }
    }
}
