//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GhiChu
    {
        public int MaGhiChu { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
        public Nullable<int> MaVanBan { get; set; }
        public string NoiDung { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
