//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiCongTruong
    {
        public int MaLoaiCT { get; set; }
        public string TenLoaiCT { get; set; }
        public Nullable<int> CapCongTruong { get; set; }
        public Nullable<int> ThuTu { get; set; }
    }
}
