//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuotXemTai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LuotXemTai()
        {
            this.CT_LuotXemTai = new HashSet<CT_LuotXemTai>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MaVanBan { get; set; }
        public Nullable<System.DateTime> NgayXT { get; set; }
        public Nullable<decimal> LuotXem { get; set; }
        public Nullable<decimal> LuotTai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_LuotXemTai> CT_LuotXemTai { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
