//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhom_Nhanvien
    {
        public int Id { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhomTV NhomTV { get; set; }
    }
}
