//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongHop
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Color { get; set; }
        public string Resources { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Ordering { get; set; }
    }
}
