//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyVanBanEntities : DbContext
    {
        public QuanLyVanBanEntities()
            : base("name=QuanLyVanBanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<CauHinh> CauHinhs { get; set; }
        public virtual DbSet<CT_LuotXemTai> CT_LuotXemTai { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DMBanLanhDao> DMBanLanhDaos { get; set; }
        public virtual DbSet<DMPhongBan> DMPhongBans { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<FAQ_NoiDung> FAQ_NoiDung { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<GhiChu> GhiChus { get; set; }
        public virtual DbSet<LichHop> LichHops { get; set; }
        public virtual DbSet<LichHop_BLD> LichHop_BLD { get; set; }
        public virtual DbSet<LoaiTaiLieu> LoaiTaiLieux { get; set; }
        public virtual DbSet<LuotXemTai> LuotXemTais { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Nhom_FAQ> Nhom_FAQ { get; set; }
        public virtual DbSet<Nhom_Nhanvien> Nhom_Nhanvien { get; set; }
        public virtual DbSet<Nhom_Quyen> Nhom_Quyen { get; set; }
        public virtual DbSet<NhomTV> NhomTVs { get; set; }
        public virtual DbSet<PhongHop> PhongHops { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<Revision> Revisions { get; set; }
        public virtual DbSet<TaiLieu> TaiLieux { get; set; }
        public virtual DbSet<ThuMuc> ThuMucs { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
        public virtual DbSet<VB_VBCC> VB_VBCC { get; set; }
        public virtual DbSet<VB_VBHD> VB_VBHD { get; set; }
        public virtual DbSet<VB_VBLQ> VB_VBLQ { get; set; }
        public virtual DbSet<VB_VBSD> VB_VBSD { get; set; }
        public virtual DbSet<VBLuuTru> VBLuuTrus { get; set; }
        public virtual DbSet<VB_BMLQ> VB_BMLQ { get; set; }
        public virtual DbSet<NhatKy> NhatKies { get; set; }
        public virtual DbSet<PdfPage> PdfPages { get; set; }
    }
}
