//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        public int MaRevision { get; set; }
        public Nullable<int> MaVanBan { get; set; }
        public string TenRevision { get; set; }
        public string fileTV { get; set; }
        public string fileTA { get; set; }
    
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
