//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiLieu()
        {
            this.GhiChus = new HashSet<GhiChu>();
            this.LuotXemTais = new HashSet<LuotXemTai>();
            this.Revisions = new HashSet<Revision>();
            this.VB_VBCC = new HashSet<VB_VBCC>();
            this.VB_VBCC1 = new HashSet<VB_VBCC>();
            this.VB_VBHD = new HashSet<VB_VBHD>();
            this.VB_VBHD1 = new HashSet<VB_VBHD>();
            this.VB_VBLQ = new HashSet<VB_VBLQ>();
            this.VB_VBLQ1 = new HashSet<VB_VBLQ>();
            this.VB_VBSD = new HashSet<VB_VBSD>();
            this.VB_VBSD1 = new HashSet<VB_VBSD>();
            this.VBLuuTrus = new HashSet<VBLuuTru>();
            this.VB_BMLQ = new HashSet<VB_BMLQ>();
            this.VB_BMLQ1 = new HashSet<VB_BMLQ>();
        }
    
        public int MaTaiLieu { get; set; }
        public string TenTaiLieu { get; set; }
        public string NoiDungTV { get; set; }
        public string NoiDungTA { get; set; }
        public string NoiDungTomTat { get; set; }
        public string SoHieu { get; set; }
        public Nullable<int> LoaiVanBan { get; set; }
        public Nullable<int> NoiBanHanh { get; set; }
        public string NguoiKy { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> PhongBan { get; set; }
        public string fileGOC { get; set; }
        public string filePDF { get; set; }
        public string fileDOCV { get; set; }
        public string fileDOCA { get; set; }
        public Nullable<bool> BaoMat { get; set; }
        public Nullable<int> LanHieuChinh { get; set; }
        public Nullable<System.DateTime> NgayTaiLen { get; set; }
        public string MaHieu { get; set; }
        public Nullable<int> LanBanHanh { get; set; }
        public string DonViApDung { get; set; }
    
        public virtual DMPhongBan DMPhongBan { get; set; }
        public virtual DMPhongBan DMPhongBan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GhiChu> GhiChus { get; set; }
        public virtual LoaiTaiLieu LoaiTaiLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuotXemTai> LuotXemTais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revision> Revisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_VBCC> VB_VBCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_VBCC> VB_VBCC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_VBHD> VB_VBHD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_VBHD> VB_VBHD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_VBLQ> VB_VBLQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_VBLQ> VB_VBLQ1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_VBSD> VB_VBSD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_VBSD> VB_VBSD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VBLuuTru> VBLuuTrus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_BMLQ> VB_BMLQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VB_BMLQ> VB_BMLQ1 { get; set; }
    }
}
