//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TinTuc()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int MaTinTuc { get; set; }
        public Nullable<int> LoaiTinTuc { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public string TieuDe { get; set; }
        public string HinhDaiDien { get; set; }
        public string NoiDungThuGon { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> ChoPhepBinhLuan { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotThich { get; set; }
        public Nullable<int> LuotBinhLuan { get; set; }
        public Nullable<bool> TinHot { get; set; }
        public Nullable<System.DateTime> EndHotDate { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> MaLoaiCT { get; set; }
        public Nullable<bool> BaoMat { get; set; }
        public string filePDF { get; set; }
        public string fileDOCV { get; set; }
        public string fileDOCA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}
